# Generated by Django 3.2.5 on 2022-06-02 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MajorPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_user', models.CharField(max_length=20, verbose_name='创建者')),
                ('platform', models.CharField(max_length=20, unique=True, verbose_name='平台')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='SubProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_user', models.CharField(max_length=20, verbose_name='创建者')),
                ('model', models.CharField(max_length=20, unique=True, verbose_name='车辆型号')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('platform_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtest.majorplatform', to_field='platform', verbose_name='关联的平台')),
            ],
        ),
        migrations.CreateModel(
            name='FunctionModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(max_length=20, unique=True, verbose_name='功能模块')),
                ('model_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtest.subprojects', to_field='model', verbose_name='关联的车辆型号')),
            ],
        ),
    ]
