# Generated by Django 3.2.5 on 2022-06-02 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='majorplatform',
            old_name='creat_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='majorplatform',
            old_name='creat_user',
            new_name='create_user',
        ),
        migrations.RenameField(
            model_name='subprojects',
            old_name='creat_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='subprojects',
            old_name='creat_user',
            new_name='create_user',
        ),
    ]
