# Generated by Django 3.2.5 on 2022-06-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0003_auto_20220602_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subprojects',
            name='create_user',
            field=models.CharField(choices=[('Jiaying Huang', '黄嘉颖')], max_length=20, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='subprojects',
            name='model',
            field=models.CharField(choices=0, max_length=20, unique=True, verbose_name='车辆型号'),
        ),
    ]
