# Generated by Django 3.2.5 on 2022-06-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0004_auto_20220602_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subprojects',
            name='model',
            field=models.CharField(choices=[('CN200', 'CN200')], max_length=20, unique=True, verbose_name='车辆型号'),
        ),
    ]
