# Generated by Django 3.2.5 on 2022-06-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0005_alter_subprojects_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subprojects',
            name='model',
            field=models.CharField(choices=[('CN200_CN200', 'CN200_CN200')], max_length=20, unique=True, verbose_name='车辆型号'),
        ),
    ]
