# Generated by Django 3.2.5 on 2022-06-02 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0006_alter_subprojects_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionmodules',
            name='function',
            field=models.CharField(choices=[('售后', '售后数据分析'), ('排放', '排放数据分析'), ('热管理', '热管理数据分析')], max_length=20, verbose_name='功能模块'),
        ),
        migrations.CreateModel(
            name='AnalyticsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=256, verbose_name='数据')),
                ('analytics', models.TextField(verbose_name='结果分析')),
                ('function_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtest.functionmodules', verbose_name='所属功能模块')),
                ('models_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtest.subprojects', to_field='model', verbose_name='所属车型')),
                ('platform_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtest.majorplatform', to_field='platform', verbose_name='所属平台')),
            ],
        ),
    ]
