# Generated by Django 3.2.5 on 2022-07-26 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webtest', '0008_auto_20220726_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_user', models.CharField(choices=[('Jiaying Huang', '黄嘉颖')], max_length=20, verbose_name='创建者')),
                ('platform', models.CharField(choices=[('CN100', 'CN100平台'), ('CN180', 'CN180平台'), ('CN200', 'CN200平台'), ('CN300', 'CN300平台'), ('N', 'N平台'), ('SGMW_950', '950平台')], max_length=20, unique=True, verbose_name='平台')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='SubProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_user', models.CharField(choices=[('Jiaying Huang', '黄嘉颖')], max_length=20, verbose_name='创建者')),
                ('model', models.CharField(choices=[('CN200_CN200', 'CN200_CN200')], max_length=20, unique=True, verbose_name='车辆型号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('platform_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtest.majorplatform', to_field='platform', verbose_name='关联的平台')),
            ],
        ),
        migrations.CreateModel(
            name='FunctionModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(choices=[('售后', '售后数据分析'), ('排放', '排放数据分析'), ('热管理', '热管理数据分析')], max_length=20, verbose_name='功能模块')),
                ('model_info', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webtest.subprojects', to_field='model', verbose_name='关联的车辆型号')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=256, verbose_name='数据')),
                ('analytics', models.TextField(verbose_name='结果分析')),
                ('function_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtest.functionmodules', verbose_name='所属功能模块')),
                ('models_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtest.subprojects', to_field='model', verbose_name='所属车型')),
                ('platform_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtest.majorplatform', to_field='platform', verbose_name='所属平台')),
            ],
        ),
    ]
