# Generated by Django 3.2.5 on 2022-07-26 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0010_platformmodelcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlatformModelCode',
        ),
    ]
