# Generated by Django 3.2.5 on 2022-07-26 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0011_delete_platformmodelcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformModelCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='车型特征数据')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webtest.platformmodelcode', verbose_name='自关联标识')),
            ],
        ),
    ]
