# Generated by Django 3.2.5 on 2022-07-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0012_platformmodelcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.SmallIntegerField(choices=[(1, '红标'), (2, '银标'), (3, '光标'), (4, '宝骏'), (5, '新宝骏')], verbose_name='品牌')),
                ('platform', models.SmallIntegerField(choices=[(1, 'CN100平台'), (2, 'CN180平台'), (3, 'CN200平台'), (4, 'CN300平台'), (5, 'N平台'), (6, '950平台')], verbose_name='车型平台')),
                ('name', models.SmallIntegerField(choices=[(1, '730S'), (2, '310S'), (3, '730M'), (4, '220M')], verbose_name='车型')),
                ('engine', models.SmallIntegerField(choices=[(1, 'N15A'), (2, 'N15T'), (3, 'S15T'), (4, 'LJ2.0T')], verbose_name='发动机类型')),
                ('gearbox', models.SmallIntegerField(choices=[(1, 'MT'), (2, 'CVT'), (3, 'GF6'), (4, '混动')], verbose_name='变速箱类型或混动')),
                ('EmissionRegulations', models.SmallIntegerField(choices=[(1, '国五'), (2, '国六A'), (3, '国六B')], verbose_name='排放法规')),
                ('sop_time', models.DateField(verbose_name='SOP时间')),
                ('ProjectProcess', models.SmallIntegerField(choices=[(1, '台架数据锁定'), (2, 'VBC和排温检查标定'), (3, '排放标定和GPF标定'), (4, 'OBD标定'), (5, '数据固化')], verbose_name='项目进度')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
