# Generated by Django 3.2.5 on 2022-07-26 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0013_projectinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyticsdata',
            options={'verbose_name': '分析数据存储', 'verbose_name_plural': '分析数据存储'},
        ),
        migrations.AlterModelOptions(
            name='functionmodules',
            options={'verbose_name': '功能模块', 'verbose_name_plural': '功能模块'},
        ),
        migrations.AlterModelOptions(
            name='majorplatform',
            options={'verbose_name': '车型平台', 'verbose_name_plural': '车型平台'},
        ),
        migrations.AlterModelOptions(
            name='platformmodelcode',
            options={'verbose_name': '平台-车辆型号-车型代码自关联表', 'verbose_name_plural': '平台-车辆型号-车型代码自关联表'},
        ),
        migrations.AlterModelOptions(
            name='projectinfo',
            options={'verbose_name': '成哥的表', 'verbose_name_plural': '成哥的表'},
        ),
        migrations.AlterModelOptions(
            name='subprojects',
            options={'verbose_name': '车型', 'verbose_name_plural': '车型'},
        ),
        migrations.AlterField(
            model_name='majorplatform',
            name='platform',
            field=models.ForeignKey(limit_choices_to={'pid_id': 'null'}, on_delete=django.db.models.deletion.CASCADE, to='webtest.platformmodelcode', to_field='data', unique=True, verbose_name='平台'),
        ),
    ]
