# Generated by Django 3.2.5 on 2022-07-26 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0015_auto_20220726_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorplatform',
            name='platform',
            field=models.ForeignKey(limit_choices_to={'pid_id': 99999}, on_delete=django.db.models.deletion.CASCADE, to='webtest.platformmodelcode', to_field='data', unique=True, verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='platformmodelcode',
            name='data',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='车型特征数据'),
        ),
        migrations.AlterField(
            model_name='platformmodelcode',
            name='pid',
            field=models.ForeignKey(blank=True, default=99999, on_delete=django.db.models.deletion.CASCADE, to='webtest.platformmodelcode', verbose_name='自关联标识'),
        ),
    ]
