# Generated by Django 3.2.5 on 2022-07-26 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0023_alter_platformmodelcode_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorplatform',
            name='platform',
            field=models.ForeignKey(limit_choices_to={'pid_id': 'Null'}, on_delete=django.db.models.deletion.CASCADE, to='webtest.platformmodelcode', to_field='data', unique=True, verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='platformmodelcode',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webtest.platformmodelcode', verbose_name='自关联标识'),
        ),
    ]
