# Generated by Django 3.2.5 on 2022-07-27 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0025_alter_majorplatform_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformmodelcode',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beyond', to='webtest.platformmodelcode', verbose_name='自关联标识'),
        ),
    ]
