# Generated by Django 3.2.5 on 2022-07-27 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0026_alter_platformmodelcode_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorplatform',
            name='platform',
            field=models.CharField(choices=[('CN100', 'CN100平台'), ('CN180', 'CN180平台'), ('CN200', 'CN200平台'), ('CN300', 'CN300平台'), ('N', 'N平台'), ('SGMW_950', '950平台')], max_length=20, unique=True, verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='platformmodelcode',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beyond', to='webtest.platformmodelcode', verbose_name='自关联标识'),
        ),
    ]
