# Generated by Django 3.2.5 on 2022-07-27 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0027_auto_20220727_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platformmodelcode',
            old_name='data',
            new_name='info',
        ),
    ]
