# Generated by Django 3.2.5 on 2022-08-17 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelationshipTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(blank=True, max_length=50, null=True, verbose_name='车辆信息')),
                ('relationship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.relationshiptable', verbose_name='关系')),
            ],
            options={
                'verbose_name': '车辆商标-车型平台-车型代码-发动机型号-变速箱型号-排放法规自关联表',
                'verbose_name_plural': '车辆商标-车型平台-车型代码-发动机型号-变速箱型号-排放法规自关联表',
            },
        ),
    ]
