# Generated by Django 3.2.5 on 2022-05-30 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentgoal',
            old_name='student_id',
            new_name='student',
        ),
    ]
