# Generated by Django 3.2.5 on 2022-06-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionmodules',
            name='function',
            field=models.CharField(max_length=20, unique=True, verbose_name='功能模块'),
        ),
        migrations.AlterField(
            model_name='majorplatform',
            name='platform',
            field=models.CharField(max_length=20, unique=True, verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='subprojects',
            name='model',
            field=models.CharField(max_length=20, unique=True, verbose_name='车辆型号'),
        ),
    ]
