# Generated by Django 3.2.5 on 2022-06-02 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20220602_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subprojects',
            name='platform_info',
        ),
        migrations.DeleteModel(
            name='FunctionModules',
        ),
        migrations.DeleteModel(
            name='MajorPlatform',
        ),
        migrations.DeleteModel(
            name='SubProjects',
        ),
    ]
