# Generated by Django 3.2.5 on 2022-05-30 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_rename_student_id_studentgoal_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='时间'),
        ),
    ]
