# Generated by Django 3.2.5 on 2022-05-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_studentinfo_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='email',
            field=models.EmailField(default='123@qq.com', max_length=254, verbose_name='电子邮箱'),
        ),
    ]
