# Generated by Django 3.2.5 on 2022-08-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20220831_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emissionstandard',
            name='gearbox',
        ),
        migrations.RemoveField(
            model_name='gearbox',
            name='engine',
        ),
        migrations.AddField(
            model_name='emissionstandard',
            name='model',
            field=models.ManyToManyField(to='tests.Model'),
        ),
        migrations.AddField(
            model_name='gearbox',
            name='model',
            field=models.ManyToManyField(to='tests.Model'),
        ),
    ]
