# Generated by Django 3.2.5 on 2022-05-30 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_studentinfo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='address',
            field=models.FileField(default='0', upload_to='uploads/', verbose_name='文件地址'),
        ),
    ]
