# Generated by Django 3.2.5 on 2022-09-01 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_projectinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectInfo',
            new_name='ProjectInfo1',
        ),
    ]
