# Generated by Django 3.2.5 on 2022-05-30 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_alter_studentinfo_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgoal',
            name='student',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='tests.studentinfo', to_field='student_id'),
        ),
    ]
