# Generated by Django 3.2.5 on 2022-09-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_auto_20220901_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo1',
            name='projectProcess',
            field=models.CharField(choices=[('台架数据锁定', '台架数据锁定'), ('VBC和排温检查标定', 'VBC和排温检查标定'), ('排放标定和GPF标定', '排放标定和GPF标定'), ('OBD标定', 'OBD标定'), ('数据固化', '数据固化')], max_length=50, verbose_name='项目进度'),
        ),
    ]
