# Generated by Django 3.2.5 on 2022-05-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_alter_studentgoal_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='address',
            field=models.FileField(blank=True, db_column='文件地址', null=True, upload_to='', verbose_name='文件地址'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='email',
            field=models.EmailField(db_column='电子邮箱', default='123@qq.com', max_length=254, verbose_name='电子邮箱'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='ethnic',
            field=models.CharField(choices=[('汉', '汉'), ('壮', '壮')], db_column='民族', max_length=5, verbose_name='民族'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='name',
            field=models.CharField(db_column='姓名', max_length=10, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], db_column='性别', max_length=5, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='time',
            field=models.DateTimeField(auto_now=True, db_column='时间', verbose_name='时间'),
        ),
    ]
