# Generated by Django 3.2.5 on 2022-05-30 08:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_auto_20220530_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterSaleDataAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(db_column='分析数据主题', max_length=255, verbose_name='分析数据主题')),
                ('note', models.TextField(db_column='备注', default='无', verbose_name='备注')),
                ('file_address', models.FileField(db_column='文件地址', upload_to='', verbose_name='文件地址')),
                ('updata_time', models.DateTimeField(db_column='上传时间', default=datetime.datetime(2022, 5, 30, 8, 47, 12, 588688, tzinfo=utc), verbose_name='上传时间')),
            ],
        ),
    ]
