# Generated by Django 3.2.5 on 2022-05-30 08:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_auto_20220530_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aftersaledataanalyse',
            name='file_address',
            field=models.FileField(db_column='售后数据文件', upload_to='tests/uploads/', verbose_name='售后数据文件'),
        ),
        migrations.AlterField(
            model_name='aftersaledataanalyse',
            name='updata_time',
            field=models.DateTimeField(db_column='上传时间', default=datetime.datetime(2022, 5, 30, 8, 52, 44, 822474, tzinfo=utc), verbose_name='上传时间'),
        ),
    ]
