# Generated by Django 3.2.5 on 2022-05-30 09:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_auto_20220530_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterSaleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(db_column='分析数据主题', max_length=255, verbose_name='分析数据主题')),
                ('note', models.TextField(db_column='备注', default='无', verbose_name='备注')),
                ('file_address', models.FileField(db_column='售后数据文件', upload_to='tests/uploads/', verbose_name='售后数据文件')),
                ('updata_time', models.DateTimeField(db_column='上传时间', default=django.utils.timezone.now, verbose_name='上传时间')),
            ],
        ),
        migrations.DeleteModel(
            name='AfterSaleDataAnalyse',
        ),
    ]
