# Generated by Django 3.2.5 on 2022-05-30 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0013_auto_20220530_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterSaleDataAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file1_address', models.FileField(db_column='表', upload_to='tests/uploads/', verbose_name='表')),
                ('img1_address', models.ImageField(db_column='柱状图', upload_to='tests/uploads/', verbose_name='柱状图')),
                ('datainfo', models.ForeignKey(db_column='售后数据', on_delete=django.db.models.deletion.CASCADE, to='tests.aftersaledata')),
            ],
        ),
    ]
