# Generated by Django 3.2.5 on 2022-05-31 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0014_aftersaledataanalyse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aftersaledataanalyse',
            name='file1_address',
        ),
        migrations.RemoveField(
            model_name='aftersaledataanalyse',
            name='img1_address',
        ),
        migrations.AddField(
            model_name='aftersaledataanalyse',
            name='fault_part_histogram',
            field=models.CharField(choices=[('无', '无'), ('故障部件柱状图', '故障部件柱状图')], db_column='故障部件柱状图', default='无', max_length=10, verbose_name='故障部件柱状图'),
        ),
        migrations.AddField(
            model_name='aftersaledataanalyse',
            name='fault_part_pie',
            field=models.CharField(choices=[('无', '无'), ('故障部件饼图', '故障部件饼图')], db_column='故障部件饼图', default='无', max_length=10, verbose_name='故障部件饼图'),
        ),
        migrations.AddField(
            model_name='aftersaledataanalyse',
            name='fault_type_pie',
            field=models.CharField(choices=[('无', '无'), ('故障种类饼图', '故障种类饼图')], db_column='故障类型饼图', default='无', max_length=10, verbose_name='故障类型饼图'),
        ),
        migrations.AddField(
            model_name='aftersaledataanalyse',
            name='histogram',
            field=models.CharField(choices=[('无', '无'), ('柱状图', '柱状图')], db_column='柱状图', default='无', max_length=10, verbose_name='柱状图'),
        ),
        migrations.AddField(
            model_name='aftersaledataanalyse',
            name='pie',
            field=models.CharField(choices=[('无', '无'), ('故障部件柱状图', '故障部件柱状图')], db_column='饼图', default='无', max_length=10, verbose_name='饼图'),
        ),
    ]
