# Generated by Django 3.2.5 on 2022-05-31 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0015_auto_20220531_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureHistogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cn100', models.FileField(db_column='CN100', upload_to='tests/uploads/', verbose_name='CN100')),
                ('cn180', models.FileField(db_column='CN180', upload_to='tests/uploads/', verbose_name='CN180')),
                ('belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.aftersaledataanalyse', verbose_name='所属')),
            ],
        ),
    ]
