# Generated by Django 3.2.5 on 2022-05-31 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0016_picturehistogram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aftersaledata',
            name='file_address',
            field=models.FileField(db_column='售后数据文件', upload_to='tests/uploads/%Y/%m/%d/', verbose_name='售后数据文件'),
        ),
        migrations.AlterField(
            model_name='picturehistogram',
            name='cn100',
            field=models.FileField(db_column='CN100', upload_to='tests/uploads/%Y/%m/%d/', verbose_name='CN100'),
        ),
        migrations.AlterField(
            model_name='picturehistogram',
            name='cn180',
            field=models.FileField(db_column='CN180', upload_to='tests/uploads/%Y/%m/%d/', verbose_name='CN180'),
        ),
    ]
