# Generated by Django 3.2.5 on 2022-05-31 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0017_auto_20220531_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='picturehistogram',
            name='cn200',
            field=models.FileField(blank=True, db_column='CN200', null=True, upload_to='tests/uploads/%Y/%m/%d/CN200/', verbose_name='CN200'),
        ),
        migrations.AddField(
            model_name='picturehistogram',
            name='cn300',
            field=models.FileField(blank=True, db_column='CN300', null=True, upload_to='tests/uploads/%Y/%m/%d/CN300/', verbose_name='CN300'),
        ),
        migrations.AddField(
            model_name='picturehistogram',
            name='n',
            field=models.FileField(blank=True, db_column='N', null=True, upload_to='tests/uploads/%Y/%m/%d/N/', verbose_name='N'),
        ),
        migrations.AddField(
            model_name='picturehistogram',
            name='sgmw_950',
            field=models.FileField(blank=True, db_column='SGMW_950', null=True, upload_to='tests/uploads/%Y/%m/%d/SGMW_950/', verbose_name='SGMW_950'),
        ),
        migrations.AlterField(
            model_name='picturehistogram',
            name='cn100',
            field=models.FileField(blank=True, db_column='CN100', null=True, upload_to='tests/uploads/%Y/%m/%d/CN100/', verbose_name='CN100'),
        ),
        migrations.AlterField(
            model_name='picturehistogram',
            name='cn180',
            field=models.FileField(blank=True, db_column='CN180', null=True, upload_to='tests/uploads/%Y/%m/%d/CN180/', verbose_name='CN180'),
        ),
        migrations.CreateModel(
            name='PictureFaultPartHistogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cn100', models.FileField(blank=True, db_column='CN100', null=True, upload_to='tests/uploads/%Y/%m/%d/CN100/', verbose_name='CN100')),
                ('cn180', models.FileField(blank=True, db_column='CN180', null=True, upload_to='tests/uploads/%Y/%m/%d/CN180/', verbose_name='CN180')),
                ('cn200', models.FileField(blank=True, db_column='CN200', null=True, upload_to='tests/uploads/%Y/%m/%d/CN200/', verbose_name='CN200')),
                ('cn300', models.FileField(blank=True, db_column='CN300', null=True, upload_to='tests/uploads/%Y/%m/%d/CN300/', verbose_name='CN300')),
                ('n', models.FileField(blank=True, db_column='N', null=True, upload_to='tests/uploads/%Y/%m/%d/N/', verbose_name='N')),
                ('sgmw_950', models.FileField(blank=True, db_column='SGMW_950', null=True, upload_to='tests/uploads/%Y/%m/%d/SGMW_950/', verbose_name='SGMW_950')),
                ('belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.aftersaledataanalyse', verbose_name='所属')),
            ],
        ),
    ]
