# Generated by Django 3.2.5 on 2022-06-01 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0019_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='CN100',
            field=models.CharField(blank=True, db_column='CN100', max_length=10, null=True, verbose_name='CN100'),
        ),
        migrations.AddField(
            model_name='test',
            name='CN180',
            field=models.CharField(blank=True, db_column='CN180', max_length=10, null=True, verbose_name='CN180'),
        ),
        migrations.AddField(
            model_name='test',
            name='CN200',
            field=models.CharField(blank=True, db_column='CN200', max_length=10, null=True, verbose_name='CN200'),
        ),
        migrations.AddField(
            model_name='test',
            name='CN300',
            field=models.CharField(blank=True, db_column='CN300', max_length=10, null=True, verbose_name='CN300'),
        ),
        migrations.AddField(
            model_name='test',
            name='N',
            field=models.CharField(blank=True, db_column='N', max_length=10, null=True, verbose_name='N'),
        ),
        migrations.AddField(
            model_name='test',
            name='SGMW_950',
            field=models.CharField(blank=True, db_column='SGMW_950', max_length=10, null=True, verbose_name='SGMW_950'),
        ),
    ]
